name: Frontend CI/CD Pipeline (Node 22)

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 빌드 타임 환경 변수 생성
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_BE_BASE_URL=${{ secrets.NEXT_PUBLIC_BE_BASE_URL }}" >> apps/web/.env
          echo "NEXT_PUBLIC_FE_BASE_URL=${{ secrets.NEXT_PUBLIC_FE_BASE_URL }}" >> apps/web/.env
          echo "NEXT_PUBLIC_CLOUD_INARY_URL=${{ secrets.NEXT_PUBLIC_CLOUD_INARY_URL }}" >> apps/web/.env
          echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> apps/web/.env
          echo "NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET }}" >> apps/web/.env
          echo "NEXT_PUBLIC_GOOGLE_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_GOOGLE_REDIRECT_URI }}" >> apps/web/.env

      # Docker Hub 로그인 (계정: byeoninjeong)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 이미지 빌드 및 푸시 (이미지명: frontend-server)
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend-server:latest

      # EC2 서버 배포 명령
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 팀원분이 설정한 서버 내 경로
            cd /home/ec2-user/dev/helloworld-platform 
            # 도커 컴포즈로 프론트엔드 업데이트
            docker compose -f docker-compose.dev.yml pull frontend
            docker compose -f docker-compose.dev.yml up -d frontend
            docker image prune -f
